<?php
/** @var \Insead\CustomCheckout\Block\Checkout $block */
?>
<div id="insead-custom-checkout" class="insead-checkout-wrapper" data-bind="scope: 'inseadCheckout'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#insead-custom-checkout": {
        "Magento_Ui/js/core/app": {
            "components": {
                "inseadCheckout": <?= /* @noEscape */ $block->getJsonConfig() ?>
            }
        }
    }
}
</script>
